field.field.*.*.*.third_party.field_config_cardinality:
  type: mapping
  label: 'Cardinality per bundle'
  mapping:
    cardinality_config:
      type: string
      label: 'Cardinality configuration'