name: Field Config Cardinality
core: 8.x
core_version_requirement: ^8 || ^9
description: Allow apply cardinality on Field Config (Cardinality Instance)
package: field
type: module

# Information added by Drupal.org packaging script on 2020-11-10
version: '8.x-1.1'
project: 'field_config_cardinality'
datestamp: 1605047070
