_core:
  default_config_hash: O6zgigampe1cT-2o46imYVk1gchK_XszjWhzD-YSskY
default_challenge: recaptcha/reCAPTCHA
description: 'Warning: Extraneous information may be read while using a screen reader on the RECAPTCHA below.'
administration_mode: false
allow_on_admin_pages: false
add_captcha_description: true
default_validation: 1
persistence: 0
enable_stats: false
log_wrong_responses: false
