_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  adminimal_overrides: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  book: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  comment: 0
  config: 0
  config_filter: 0
  config_split: 0
  contact: 0
  content_moderation: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  datetime: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  externalauth: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filefield_paths: 0
  filter: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  investor_gallery_slideshow: 0
  investor_replicate_settings: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_datepicker: 0
  jquery_ui_slider: 0
  jquery_ui_touch_punch: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  link: 0
  linkit: 0
  login_security: 0
  media: 0
  media_entity_download: 0
  menu_block: 0
  menu_block_title: 0
  menu_link_attributes: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  no_autocomplete: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  path_redirect_import: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  replicate: 0
  replicate_actions: 0
  replicate_ui: 0
  rh_media: 0
  role_log: 0
  search_api: 0
  search_api_autocomplete: 0
  search_api_db: 0
  sec_brokerage_account_statement: 0
  sec_calculator: 0
  sec_compound_calculator: 0
  sec_iapd_widget: 0
  sec_investor_general: 0
  sec_news_investor: 0
  sec_rmd_calculator: 0
  sec_savings_calculator: 0
  sec_twigextensions: 0
  shortcut: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  simple_sitemap_views: 0
  syslog: 0
  system: 0
  taxonomy: 0
  text: 0
  tippy_lib: 0
  token: 0
  toolbar: 0
  twig_tweak: 0
  twitter_block: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  viewfield: 0
  views_autocomplete_filters: 0
  views_ui: 0
  workflows: 0
  extlink: 1
  http_response_headers: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  paragraphs: 11
  investor_build: 999
  standard: 1000
theme:
  seven: 0
  secgov: 0
  investor: 0
  adminimal_theme: 0
profile: standard
