_core:
  default_config_hash: 2XQ7CJCL5AHhVMjWOiULKqWXRGLD3fYFGQGgH_DbNDg
hash_key: auHash
duration: 172800
cleanup_expired_tokens: true
cleanup_expired_tokens_period: '-1 days'
modify_http_headers: {  }
