cacheexclude_list: "/oia/training\r\n/oia/training/*\r\n/node/*/revisions\r\n/node/*/revisions/*/view\r\n/node/*/revisions/*/revert"
cacheexclude_node_types:
  article_type: 0
  data_distribution: 0
  data_visualization: 0
  event: 0
  file: 0
  govdelivery_form: 0
  image: 0
  landing_page: 0
  link: 0
  news: 0
  news_type: 0
  page: 0
  sec_alert: 0
  sec_hero: 0
  secarticle: 0
  secperson: 0
  spotlight: 0
  video: 0
  webcast: 0
