_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
module:
  a11y_tabs: 0
  access_unpublished: 0
  acquia_connector: 0
  acquia_purge: 0
  acquia_search: 0
  action: 0
  address: 0
  addtocalendar: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  aggregator: 0
  allowed_formats: 0
  anchor_link: 0
  automated_cron: 0
  ban: 0
  better_exposed_filters: 0
  big_pipe: 0
  block: 0
  block_content: 0
  breakpoint: 0
  cacheexclude: 0
  cer: 0
  ckeditor: 0
  color: 0
  comment: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_filter: 0
  config_split: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  contextual: 0
  core_context: 0
  core_event_dispatcher: 0
  cshs: 0
  csv_serialization: 0
  ctools: 0
  ctools_block: 0
  datatables: 0
  datetime: 0
  dynamic_page_cache: 0
  easy_breadcrumb: 0
  editor: 0
  embed: 0
  empty_fields: 0
  entity_embed: 0
  entity_reference_revisions: 0
  environment_indicator: 0
  environment_indicator_ui: 0
  fakeobjects: 0
  feeds: 0
  field: 0
  field_config_cardinality: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_download_link: 0
  file_download_link_media: 0
  filefield_paths: 0
  filter: 0
  fixed_text_link_formatter: 0
  flag: 0
  flag_bookmark: 0
  flexslider: 0
  flexslider_views: 0
  geocoder: 0
  geocoder_address: 0
  geocoder_field: 0
  geocoder_geofield: 0
  geofield: 0
  hal: 0
  help: 0
  history: 0
  hook_event_dispatcher: 0
  http_response_headers: 0
  image: 0
  inline_entity_form: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_draggable: 0
  jquery_ui_droppable: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jquery_ui_touch_punch: 0
  layout_builder: 0
  layout_builder_customizer: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  layout_library: 0
  leaflet: 0
  leaflet_markercluster: 0
  leaflet_views: 0
  link: 0
  linkit: 0
  login_security: 0
  mailsystem: 0
  mask: 0
  media: 0
  media_entity_file_replace: 0
  media_entity_link: 0
  media_library: 0
  menu_ui: 0
  metatag: 0
  migrate: 0
  migrate_drupal: 0
  migrate_file: 0
  migrate_file_to_media: 0
  migrate_node_media: 0
  migrate_plus: 0
  migrate_source_csv: 0
  migrate_source_directory: 0
  migrate_tools: 0
  mysql: 0
  no_autocomplete: 0
  node: 0
  node_revision_delete: 0
  node_save_redirect: 0
  options: 0
  page_cache: 0
  page_manager: 0
  page_manager_ui: 0
  panelizer: 0
  panels: 0
  panels_ipe: 0
  path: 0
  path_alias: 0
  pathauto: 0
  protected_pages: 0
  purge: 0
  purge_drush: 0
  purge_processor_cron: 0
  purge_processor_lateruntime: 0
  purge_queuer_coretags: 0
  purge_tokens: 0
  purge_ui: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  recreate_block_content: 0
  redirect: 0
  redirect_404: 0
  replicate: 0
  replicate_actions: 0
  replicate_ui: 0
  responsive_image: 0
  rest: 0
  rh_node: 0
  role_log: 0
  scheduled_updates: 0
  scheduler: 0
  search: 0
  search_api: 0
  search_api_solr: 0
  sec_activity_tracker: 0
  sec_admin: 0
  sec_admin_content: 0
  sec_ba: 0
  sec_block_layout: 0
  sec_conditional_fields: 0
  sec_custom_blocks: 0
  sec_custom_libraries: 0
  sec_data_distribution: 0
  sec_data_visualization: 0
  sec_edgar: 0
  sec_event: 0
  sec_investor_general: 0
  sec_legacy_migration: 0
  sec_link_target: 0
  sec_linkit_alter: 0
  sec_migration: 0
  sec_news: 0
  sec_regulations_migration: 0
  sec_release_importer: 0
  sec_releases: 0
  sec_replicate_settings: 0
  sec_secarticle_files_migration: 0
  sec_secperson: 0
  sec_styleguide: 0
  sec_taxonomy: 0
  sec_twigextensions: 0
  sec_urls: 0
  sec_view_filter_plugin: 0
  sec_views: 0
  sec_views_plugins: 0
  sec_webcast: 0
  sec_webform: 0
  sec_workflow: 0
  serialization: 0
  shortcut: 0
  simple_block: 0
  simple_sitemap: 0
  subpathauto: 0
  swiftmailer: 0
  syslog: 0
  system: 0
  taxonomy: 0
  taxonomy_manager: 0
  telephone: 0
  text: 0
  tippy_lib: 0
  token: 0
  token_filter: 0
  toolbar: 0
  tour: 0
  twig_field_value: 0
  twig_tweak: 0
  twitter_block: 0
  ui_patterns: 0
  ui_patterns_field_formatters: 0
  ui_patterns_field_group: 0
  ui_patterns_layouts: 0
  ui_patterns_library: 0
  ui_patterns_settings: 0
  ui_patterns_views: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_wysiwyg: 0
  views_autocomplete_filters: 0
  views_data_export: 0
  views_ifempty: 0
  views_taxonomy_term_name_depth: 0
  views_ui: 0
  webform: 0
  webform_attachment: 0
  webform_location_geocomplete: 0
  webform_node: 0
  webform_templates: 0
  webform_ui: 0
  workbench: 0
  workbench_access: 0
  workbench_moderation: 0
  workbench_moderation_actions: 0
  ds: 1
  extlink: 1
  menu_link_content: 1
  ds_extras: 2
  externalauth: 10
  views: 10
  paragraphs: 11
  tvi: 15
  standard: 1000
  sec_build: 9999
theme:
  bartik: 0
  seven: 0
  adminimal_theme: 0
  secgov: 0
  stable: 0
  classy: 0
  uswds: 0
  uswds_sec: 0
profile: standard
