_core:
  default_config_hash: rHbHZIIF9TP3H2Vs37uCHz4Gm4phULg0rQ_OKihxJfM
extlink_exclude_admin_routes: false
extlink_target: false
extlink_target_no_override: false
extlink_nofollow: false
extlink_follow_no_override: false
extlink_subdomains: true
extlink_alert: true
extlink_alert_text: 'You are now leaving the SEC Website. The link you have selected is located on another server. Please click on the OK button below to proceed to the selected site. The SEC does not endorse this web site, its sponsor, or any of the policies, activities, products, or services offered on the site or by any advertiser on the site.'
extlink_exclude: '.*\.gov|http://www.xbrl.org/utr/2013-05-17/utr.xml|http://www.xbrl.org/dtr/type/numeric-2009-12-16.xsd|http://www.xbrl.org/dtr/type/nonNumeric-2009-12-16.xsd|https://secir.secure.force.com/ombudsman/OMMSForm'
extlink_include: ''
extlink_class: '0'
extlink_label: '(link is external)'
extlink_img_class: false
extlink_css_exclude: .data-exempt
extlink_css_explicit: ''
extlink_mailto_class: '0'
extlink_mailto_label: '(link sends email)'
