_core:
  default_config_hash: mtrOBzlvDBXdkwi4lmDKH2S7qxEQo_8W2ca-vBEXLWE
langcode: en
password:
  per_page_or_global: per_page_password
  protected_pages_session_expire_time: '120'
email:
  subject: 'Access to this Drupal page has been granted, please see details below'
  body: "Dear new user,\r\n\r\nAccess to this Drupal page has been created and is protected by password. Please find the details below:-\r\n\r\nPage Url = [protected-page-url]\r\n\r\nPage Password = SECTechnicalAssistance\r\n\r\nThank you.\r\n[site-name]"
others:
  protected_pages_title: 'Protected Page'
  protected_pages_description: 'The page you are trying to view is password protected. Please enter the password below to proceed.'
  protected_pages_password_label: 'Enter Password'
  protected_pages_submit_button_text: Authenticate
  protected_pages_incorrect_password_msg: 'Incorrect password!'
