_core:
  default_config_hash: ddsJZVNkrueJsDMhfOq7YDPRIQS0yaG80u4X_tedHDo
max_links: 4000
cron_generate: true
cron_generate_interval: 12
generate_duration: 60000
remove_duplicates: true
skip_untranslated: true
xsl: true
base_url: ''
default_variant: default
custom_links_include_images: false
excluded_languages: {  }
enabled_entity_types:
  - node
  - media
entities_per_queue_item: 50
