features:
  node_user_picture: 0
  comment_user_picture: 0
  comment_user_verification: 0
  favicon: 1
logo:
  use_default: 0
  path: 'public://sec-logo_0.png'
favicon:
  use_default: 1
uswds_header_style: extended
uswds_header_mega: 1
uswds_header_mega_display_second: 1
uswds_government_banner: 1
uswds_government_banner_mil: 0
uswds_footer_style: big
uswds_footer_agency: 1
uswds_footer_agency_name: 'U.S. Securities Exchange Commission'
uswds_footer_agency_url: /
uswds_footer_agency_logo: ''
uswds_contact_center: ''
uswds_email: ''
uswds_phone: ''
uswds_facebook: /opa/socialmedia
uswds_twitter: /opa/socialmedia
uswds_youtube: 'https://www.youtube.com/user/SECViews/videos'
uswds_rss: /about/secrss
uswds_paragraphs_edge_to_edge: 0
uswds_menu_accordion_duplicate_parent: 1
uswds_menu_bypass:
  primary_menu: 0
  secondary_menu: 0
  sidebar_first: 0
  sidebar_second: 0
  footer_menu: 0
uswds_search_bypass: 0
uswds_search_style: small
uswds_form_optional_label: 0
button_sizes: "c-button|Standard\r\nc-button.c-button--small|Small\r\nc-button.c-button--large|Large"
button_styles: "c-button|Primary\r\nc-button.c-button--secondary|Secondary\r\nc-button.c-button--outline|Outline\r\nc-button.c-button--danger|Danger"
include_current_page_in_breadcrumb: 1
