<?php

/**
 * Alter the results of an embedded entity build array.
 *
 * This hook is called after the content has been assembled in a structured
 * array and may be used for doing processing which requires that the complete
 * block content structure has been built.
 *
 * @param array &$build
 *   A renderable array representing the embedded entity content.
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The embedded entity object.
 * @param array $context
 *   The context array.
 */
function sec_data_visualization_entity_embed_alter(array &$build, \Drupal\Core\Entity\EntityInterface $entity, array &$context) {
  if (isset($build) && $entity->bundle() === 'data_visualization') {
    $settings = [
      'message'=> 'Data Visualization cannot be embedded in Article Type other than Data Highlight.',
      'title'=> 'Warning!',
      'classes' => 'custom-ui-widget-header-warning'
    ];
    $build['#attached']['library'][] = 'sec_data_visualization/sec_data_visualization.toastr';
    $build['#attached']['drupalSettings']['embed']['alert'] = $settings;
  }
}
